version: "2"

services:
  ingestion_container:
      container_name: ingestion_public_s3_to_landing_container
      build: 
            context: ./ingestion/s3_to_landing
            dockerfile: Dockerfile
      volumes:
              - stream_landing:/WORKING_DIR/landing/:rw

  move_landing_to_raw_container:
    container_name: move_landing_to_raw_container
    build: 
          context: ./ingestion/landing_to_raw
          dockerfile: Dockerfile
    volumes:
            - stream_landing:/WORKING_DIR/landing/:rw
            - stream_raw:/WORKING_DIR/raw/:rw
  #   depends_on:
  #     - ingestion_container
  #   entrypoint: ["sh", "-c", "while ! docker ps -a | grep 'ingestion_container.*Exited'; do sleep 1; done; echo 'ingestion_container has finished, starting move_landing_to_raw_container'; exec python landing_to_raw.py"]


  ed-pyspark-jupyter:
    image: jupyter/pyspark-notebook:x86_64-python-3.11
    user: root
    container_name: ed-pyspark-jupyter-lab
    ports:
      - 8888:8888
      - 4040:4040
    environment:
      JUPYTER_PORT: 8888
      SPARK_UI_PORT: 4040
      GRANT_SUDO: yes
    volumes:
      - stream_raw:/home/jovyan/raw/:rw
      - ./Processing:/home/jovyan/:rw
      - stream_output:/home/jovyan/output/:rw
      - runtime_log:/home/jovyan/runtime_log/:rw


volumes:
  stream_landing:
    driver: local
    name: stream_landings
    driver_opts:
      type: none
      device: ./data/landing
      o: bind

  stream_raw:
    driver: local
    name: stream_raw
    driver_opts:
      type: none
      device: ./data/raw
      o: bind

  stream_output:
    driver: local
    name: stream_output
    driver_opts:
      type: none
      device: ./data/output
      o: bind

  runtime_log:
    driver: local
    name: runtime_log
    driver_opts:
      type: none
      device: ./runtime_log/
      o: bind